name: Glue Work Tracker Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Glue Work Bot
        run: python glue_work_bot/main.py

      - name: Authenticate Git
        run: |
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git config user.name "glue-work-tracker-bot"
            git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create branch with results
        run: |
            git checkout -B glue-work-contributor-results
            git add glue_work_bot_data/glue_work_report.md glue_work_bot_data/contributor_list.md
            git commit -m "Update glue work contributor results" || echo "No changes to commit"
            git push --force origin glue-work-contributor-results

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Update glue work contributor results
            title: Update glue work contributor results
            body: This PR was automatically generated by the Glue Work Tracker Bot.
            branch: glue-work-contributor-results
            base: main
